datasource:
  default: ${APP_ENV} #development

  development:
    username: sa
    password: sa
    url: "jdbc:h2:./database"

  production:
    username: ${PGUSER} #${JDBC_DATABASE_USERNAME}
    password: ${PGPASSWORD} #${JDBC_DATABASE_PASSWORD}
    url: ${DATABASE_URL} #${JDBC_DATABASE_URL}

ebean:
#  migration:
#    run: true
  ddl:
    run: true
    generate: true