datasource:
  default: ${APP_ENV}

  development: # using for development H2
    username: sa
    password: sa
    url: "jdbc:h2:./database"

  production: # using for production postgres
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}

ebean:
  migration:
    run: true

#  ddl:
#    run: true
#    generate: true
#    seedSql: seed.sql